### ISSUE TITLE
Whitespace and scrollbar in Filmstrip view in develop branch

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#260] opened 2020-04-25 15:17 UTC
When in Flimstrip view in develop branch, there is whitespace at the bottom of the screen when scrolled. It appears to be size of cookie notification bar (... This website uses coolies.... I understand)

**Comment by misi** [comment] 2020-04-27 10:18
Thank you for the report! We will fix it!

**Comment by havfo** [comment] 2020-05-01 21:46
This happens because elements inside the videos in the filmstrip are too big for their respective videos and hence overflows out below.

**Comment by havfo** [comment] 2020-05-02 11:37
This is now a duplicate of #115

**Closed by havfo** 2020-05-02 11:37 UTC
Labels: bug
