### ISSUE TITLE
Login/Logout button - current develop branch

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#173] opened 2020-04-04 16:11 UTC
I have did testing and I see this:

- user already in room and uses the login button - the login button works correctly (show LOGIN when user not authenticated, LOGOUT when authenticated) - OK

- user logs is in the waiting lobby and he automatically joins the room - in the room the LOGIN button is shown, but it should be LOGOUT, as the user is authenticated - NOT OK

- user logs in on the choose name dialog - on the dialog the text of the tool-tip does not change, it is stil LOGIN (but should be LOGOUT) although the action changes to LOGOUT!!! (when I press it /auth/logout is triggered). When he enters the room (bypassing the lobby as he has just logged in, in the rooms the button shows correctly LOGOUT). - NOT OK (as far as the choose name dialog)

**Comment by havfo** [comment] 2020-04-05 19:48
As far as I can test, this is fixed now. I could not reproduce your issue nr. 2, please test again.

**Comment by Astagor** [comment] 2020-04-05 21:49
Hi, I have checked again, and you are right my issue 2 is fixed, was my error in my login.
But point 3 still exists.  In the JoinDialog.js in line 127 you have:
`title={intl.formatMessage({
id             : 'tooltip.login',
defaultMessage : 'Click to log in'
})}`

but I think it should be something like 
`title={loginTooltip}`
and somewhere before there should be the declaration:
`	const loginTooltip = 
		loggedIn ?
		intl.formatMessage({
			id             : 'tooltip.logout',
			defaultMessage : 'Log out'
		})
		:
		intl.formatMessage({
			id             : 'tooltip.login',
			defaultMessage : 'Log in'
		});`

**Comment by havfo** [comment] 2020-04-06 06:06
Thank you for all your testing!

**Closed by havfo** 2020-04-06 06:06 UTC
