### ISSUE TITLE
Feature Request: moderation without authentication

### ISSUE THREAD

**Issue by tapionx** [havfo/multiparty-meeting#435] opened 2020-05-27 07:59 UTC
OIDC is useful for sure, but it adds a layer of complexity that must be avoided in some use cases:

1. the setup of an identity provider is complex and error prone
2. storing usernames and passwords in a database raises privacy concerns and it makes harder to comply with GDPR
3. more action for the users (sign-in) means more friction in the UX

[iorestoacasa.work](https://iorestoacasa.work) is offering a videocalls for free, without authentication.
The lack of moderation features is affecting the experience for our community, because you want to be able to kick intruders or mute everyone if the room is large.

I propose a simple and effective mechanism to enable moderation roles without authentication.

When a room is created, the user is provided with a `moderation key` computed this way:
`sha256( $room_name + $cookie_secret + $room_creation_timestamp)`

Users can join the room with this moderation key as a GET parameter

`https://example.com/room-name?moderation_key=XXXXXXX`

and they will gain the `MODERATOR` role.

**Comment by edocod1** [comment] 2020-05-27 08:19
This is a duplicate of https://github.com/havfo/multiparty-meeting/issues/261

**Closed** 2020-05-27 08:37 UTC
